### ISSUE TITLE
bioconductor availability

### ISSUE THREAD

**Issue by wconnell** [Caleb-Huo/RRHO2#1]
Hi, 

Your paper several times references this package is available on bioconductor. What is the current status of this?

**Comment by Caleb-Huo** [comment]
@skurp Thanks for your question. I am not the maintainer of this package. I am forwarding your email to the maintainer. Will let you know later.

**Comment by Caleb-Huo** [comment]
@skurp Hi there:

I contacted the maintainer.
The RRHO2 package is hosted here: https://github.com/RRHO2/RRHO2
This repository (Caleb-Huo/RRHO2) is for development purpose (not complete yet), and should not be public. I will close this repo shortly.

The maintainers of RRHO2 mentioned you can install the RRHO2 package following the instruction on 
https://github.com/RRHO2/RRHO2.
They are working on put it on bioconductor.

If you have other question/request/concerns, please post them on
https://github.com/RRHO2/RRHO2/issues/new

Best,

Caleb
